### PR TITLE
add open_timeout option

### PR DESCRIPTION
**Pull request by mtanda**
In past http lib, the `open_timeout` default value is `nil`.
https://github.com/ruby/ruby/blob/v2_1_0/lib/net/http.rb#L644

And, some fluentd plugin has the option.
https://github.com/fluent/fluent-plugin-webhdfs

I think it is worthful to add.

### CODE REVIEW

**Comment by frankreno** [comment]
@mtanda : PR #14 as it was submitted before yours and now we have a conflict. I have tested your change and all looks good however, will need 2 request 2 things from you.  1) update the README with the new parameter 2) resolve the conflicts from the previous PR. Once you do that I will merge and push a new version out.

**Comment by mtanda** [comment]
@frankreno Thanks for looking :-)
I update README, and resolve conflict!

**Comment by frankreno** [comment]
@mtanda thank you! v0.0.7 is out on ruby gems with your changes.

**Comment by mtanda** [comment]
Thank you!!

**Pull request merged**
