### PR TITLE
add option to turn off adding timestamp to logs

### PR DESCRIPTION
**Pull request by from-nibly**
This addresses issue https://github.com/SumoLogic/fluentd-output-sumologic/issues/20

### CODE REVIEW

**Comment by from-nibly** [comment]
@frankreno Absolutely. How does that look?

**Comment by frankreno** [comment]
LGTM, thanks for the PR! I will get this updated in Ruby Gems by EOD. Will update here when I do.

**Comment by frankreno** [comment]
Available in 1.0.2.

**Comment by nlundbo** [comment]
Thanks for fixing this :)

**Pull request merged**
