### PR TITLE
Upgrade to 0.14 API, send with ms precision

### PR DESCRIPTION
**Pull request by pfriel-bcs**
As mentioned in this issue: https://github.com/SumoLogic/fluentd-output-sumologic/issues/11 the plugin needs to be upgraded to the 0.14 API to support millisecond precision in SumoLogic along with the dynamic ${tag_parts[1]} syntax.

This PR does the following:
- Upgrades the plugin to use the 0.14 API according to this article: https://docs.fluentd.org/v0.14/articles/plugin-update-from-v12
- Adds logic to detect if the log has been parsed with nanosecond precision and if it has send to SumoLogic with millisecond precision. Otherwise send to SumoLogic with second precision.

**Note**: I don't believe this will be backwards compatible with 0.12 so you will probably want to cut a new version (1.0.0?) that will be for 0.14 while the 0.0.x versions remain for 0.12?

### CODE REVIEW

**Comment by frankreno** [comment]
@pfriel-bcs thank you for the PR, I will review this this week.

**Comment by frankreno** [comment]
@pfriel-bcs sorry my delay in reviewing this.  I am all about this change and agree we will need to bump the version likely.  However, there are some other PRs I would like to merge before this goes into 1.0.0.  When I merge there will be a conflict.  I've tested your changes and all looks good on my end but will need to resolve the conflicts that come up.

**Comment by pfriel-bcs** [comment]
@frankreno Sounds good, thanks.

**Comment by frankreno** [comment]
@pfriel-bcs finally got this up in rubygems, https://rubygems.org/gems/fluent-plugin-sumologic_output/versions/1.0.0. Thanks again for the PR!

**Comment by pfriel-bcs** [comment]
@frankreno No prob, thanks for getting this pushed out!

**Pull request merged**
